# Generated by Django 5.1.5 on 2025-01-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
