# Generated by Django 5.1.5 on 2025-01-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_feature_image_url_feature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('category', models.CharField(choices=[('index', 'Index'), ('course', 'Course'), ('instructor', 'Instructor')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
