# Generated by Django 5.1.5 on 2025-01-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_pageimage_delete_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
