# Generated by Django 5.1.5 on 2025-02-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_description_course_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='details',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
