# Generated by Django 5.1.5 on 2025-02-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_course_details_course_duration_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='PageImage',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
