# Generated by Django 5.1.5 on 2025-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
